[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "match3_demo"
version = "0.0.1"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
    "jax>=0.5.2"
]
requires-python = ">=3.10"
readme = "README.md"
